apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: runtime-binding
  namespace: runtime-lab

subjects:
- kind: ServiceAccount
  name: runtime-app
  namespace: runtime-lab

roleRef:
  kind: Role
  name: runtime-reader
  apiGroup: rbac.authorization.k8s.io